/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const UserScriptStorage: typeof import('./src/utils/storage')['UserScriptStorage']
  const _debugger: typeof import('./src/utils/debug')['_debugger']
  const awayFromBottom: typeof import('./src/utils/scroll')['awayFromBottom']
  const download: typeof import('./src/utils/download')['download']
  const enableAutoTurningToNextPage: typeof import('./src/utils/navigating')['enableAutoTurningToNextPage']
  const enableHorizontalScroll: typeof import('./src/utils/scroll')['enableHorizontalScroll']
  const enableMiddleClickToDownload: typeof import('./src/utils/download')['enableMiddleClickToDownload']
  const getPathname: typeof import('./src/utils/navigating')['getPathname']
  const inPage: typeof import('./src/utils/navigating')['inPage']
  const isLeftclick: typeof import('./src/utils/download')['isLeftclick']
  const isMiddleclick: typeof import('./src/utils/download')['isMiddleclick']
  const isRecordWithAtLeastOneAddedHTMLElement: typeof import('./src/utils/observer')['isRecordWithAtLeastOneAddedHTMLElement']
  const mutationObserver: typeof import('./src/utils/observer')['mutationObserver']
  const nearlyScrolledToBottom: typeof import('./src/utils/scroll')['nearlyScrolledToBottom']
  const onNearlyScrolledToBottom: typeof import('./src/utils/scroll')['onNearlyScrolledToBottom']
  const openInTab: typeof import('./src/utils/navigating')['openInTab']
  const redirectedFromAnotherTab: typeof import('./src/utils/navigating')['redirectedFromAnotherTab']
  const scrollToBottom: typeof import('./src/utils/scroll')['scrollToBottom']
  const scrollToBottomAndScrollBack: typeof import('./src/utils/scroll')['scrollToBottomAndScrollBack']
  const selectElementAsync: typeof import('./src/utils/selectElementAsync')['default']
  const wait: typeof import('./src/utils/wait')['default']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Response_GM_XMLHttpRequest } from 'src/types'
  import('src/types')
}
