export function removeAutoGenerantedKeywordLinks() {
  const autoGeneratedKeywordLinks: NodeListOf<HTMLAnchorElement> = document.querySelectorAll(
    "a.RichContent-EntityWord:not(.autoGeneratedKeywordLinksRemoved)"
  )
  autoGeneratedKeywordLinks.forEach((anchor) => {
    anchor.style.display = "none"
    const container = anchor.parentElement as HTMLSpanElement
    const newSpan = document.createTextNode(anchor.textContent as string)
    container.append(newSpan)
    anchor.classList.add("autoGeneratedKeywordLinksRemoved")
    /**
     * Can't replace(delete) children(`a` included), which will cause React(zhihu) to throw errors
     * @deprecated
     */
    // container.replaceChildren(anchor.textContent as string)
  })
}

export function substituteRedirectionLinks() {
  const linksToRemoveRedirection = document.querySelectorAll(
    "a[href^='https://link.zhihu.com/?target='], a[href^='link.zhihu.com/?target=']"
  ) as NodeListOf<HTMLAnchorElement>
  linksToRemoveRedirection.forEach((linkToRemoveRedirection) => {
    const urlWithRedirection = linkToRemoveRedirection.href
    linkToRemoveRedirection.href = removeRedirection(urlWithRedirection)
  })

  function removeRedirection(url: string) {
    const urlRemovingRedirection = url
      .replace("https://link.zhihu.com/?target=", "")
      .replace("link.zhihu.com/?target=", "")
    return decodeURIComponent(urlRemovingRedirection)
  }
}
